package keys

// KMS-backed key providers.
//
// The repository has no KMS client today (the AWS SDK is only used for
// Bedrock), so none is shipped. A KMS provider implements KeyProvider and is
// installed at startup before anything encrypts or signs:
//
//	keys.DataKeys = myKMSProvider     // e.g. data keys generated by KMS
//	keys.SigningRoots = myKMSProvider // GenerateDataKey, the wrapped copy stored in config
//
// A typical implementation keeps, per version, a KMS-wrapped 32-byte data key
// (from configuration or a table), unwraps it with KMS Decrypt once at
// startup and serves it from memory through Current / ByVersion. Ciphertexts
// and tokens only record the version (key_version column, "tnk<v>:" prefix,
// JWT kid), so moving from EnvKeyProvider to KMS needs no data migration:
// register the existing key as a KMS-wrapped version, or rotate to a new
// version and let the re-encryption job rewrite the rows.
