FROM amazonlinux:2023
RUN dnf install -y ca-certificates tzdata git unzip shadow-utils && dnf clean all
ENV TZ=Asia/Singapore
WORKDIR /app
ARG TARGETARCH
COPY linux-${TARGETARCH}/iac-platform .
EXPOSE 8080 8090
ENTRYPOINT ["./iac-platform"]
