FROM amazonlinux:latest
ENV TZ=Asia/Singapore
RUN yum install -y unzip git && update-ca-trust && mkdir -p /tmp/.terraform.d/plugin-cache
ARG TARGETARCH
COPY linux-${TARGETARCH}/iac-agent /tmp/agent
ENTRYPOINT ["/tmp/agent"]
